#!/usr/bin/env php
<?php
/**
 * Stub artisan untuk demo latihan.
 * Perintah yang didukung: serve
 */
$command = $argv[1] ?? null;

if ($command === 'serve') {
    $host = '0.0.0.0';
    $port = '8000';
    foreach ($argv as $arg) {
        if (str_starts_with($arg, '--host=')) {
            $host = substr($arg, 7);
        }
        if (str_starts_with($arg, '--port=')) {
            $port = substr($arg, 7);
        }
    }
    $public = __DIR__ . '/public';
    $router = $public . '/index.php';
    echo "Laravel Praktikum (demo MVC) berjalan di http://{$host}:{$port}\n";
    passthru('php -S ' . escapeshellarg($host . ':' . $port) . ' -t ' . escapeshellarg($public) . ' ' . escapeshellarg($router));
    exit;
}

echo "Artisan demo.\n";
echo "Gunakan: php artisan serve --host=0.0.0.0 --port=8000\n";
echo "Untuk Laravel penuh: composer create-project laravel/laravel .\n";
